### ISSUE TITLE
Nicely done! Some recommendations to consider :)

### ISSUE THREAD

**Issue by Baroshem** [markus-gx/nuxt-swell#1]
First of all, big kudos for developing your very first module!

I really enjoy looking at it and I think it has a potential to help developers built better storefronts.

Below, I listed some recommendations that you may add to your module that can make it a bit better ;)

1. Composables should start with `useSomething`. I am a big fan of simple composables that do one thing only so they are easier to test and maintain. useSwell work really well, but for product and products fetch I think it would require some refactor. In my algolia module I am using the name `useAlgoliaSearch` where I destructure it in a way like this `const { result, search } = useAlgoliaSearch('index_name')`.  It allows the user to define when he would like to fetch the data (for example, maybe he would like to fetch it on onMounted hook instead of useAsyncData. But you can also keep it as a composable that will just fetch the results and name it for example: `useSwellProducts` or `useSwellProduct`. In here, you could do something similar to what Storyblok did in their composable (trigger either useAsyncData or onMounted inside based on condition). I think it will be easier then to distinguish composables from your module inside a nuxt application.
2. Pass options apart from the mandatory key and id. In your configuration, I can see that you have this useCamelCase. I would recommend to add it to the `options` object inside configuration.  Thanks to that, when you develop more configuration options that are not mandatory for the users to set, you will just populate the options object instead of the main configuration.
```ts
swell: {
  storeId: "YOUR_STORE_ID",
  apiKey: "YOUR_PUBLIC_ACCESS_TOKEN",
  options?: {
    useCamelCase: true //Default is true change it to false to switch to snake_case responses,
    someOtherOption in the future
  }
}
```
4. Full module options type. I would recommend to keep your module configuration type up to date with the actual configuration. Nuxt 3 has a great TS support so it would be great to have a typing support for all configuration and separate composables :)

Optional (later):
1. Write Docus docs for the module with examples of usage.
2. Write content about your module (even a simple dev.to article)
3. Create a simple storefront app with this module implemented.

And that basically it! This module serves its purpose even now, so by adding these recommendations I think you will make it even better. With time, I would add more composable to fetch certain data (like category, user, checkout, etc) so that users will have less steps to do in order to build their storefronts.

**Comment by markus-gx** [comment]
Refactored and added your suggestions. Thanks!!!

Resolved with 9001f4f8741a73b3f7e3b142238633921657fcd2 & bf7b769315fb77a30b3ad4f4940098d33b0d760e
